---
- name: install unzip
  package: name=unzip state=present
  become: true

- name: download gradle
  unarchive:
    src: https://services.gradle.org/distributions/gradle-{{ gradle_version }}-all.zip
    dest: /usr/local/share/
    remote_src: true
    creates: /usr/local/share/gradle-{{ gradle_version }}/bin/gradle
  become: true

- name: symlink gradle
  file:
    state: link
    src: /usr/local/share/gradle-{{ gradle_version }}/bin/gradle
    dest: /usr/local/bin/gradle
    owner: root
    group: root
  become: true
